['/home/ubuntu/environment/BuMarket', '/home/ubuntu/environment/AlwaysOnServer/lib/python36.zip', '/home/ubuntu/environment/AlwaysOnServer/lib/python3.6', '/home/ubuntu/environment/AlwaysOnServer/lib/python3.6/lib-dynload', '/usr/lib/python3.6', '/home/ubuntu/environment/AlwaysOnServer/lib/python3.6/site-packages']
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
# Unable to inspect table 'imagetb'
# The error was: ORA-00904: "IDENTITY_COLUMN": invalid identifier
# Unable to inspect table 'liketb'
# The error was: ORA-00904: "IDENTITY_COLUMN": invalid identifier
# Unable to inspect table 'producttb'
# The error was: ORA-00904: "IDENTITY_COLUMN": invalid identifier
# Unable to inspect table 'proimagetb'
# The error was: ORA-00904: "IDENTITY_COLUMN": invalid identifier
# Unable to inspect table 'saletb'
# The error was: ORA-00904: "IDENTITY_COLUMN": invalid identifier
# Unable to inspect table 'test'
# The error was: ORA-00904: "IDENTITY_COLUMN": invalid identifier
# Unable to inspect table 'userimagetb'
# The error was: ORA-00904: "IDENTITY_COLUMN": invalid identifier
# Unable to inspect table 'usertb'
# The error was: ORA-00904: "IDENTITY_COLUMN": invalid identifier
